// <auto-generated />
namespace CP.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deneme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deneme));
        
        string IMigrationMetadata.Id
        {
            get { return "202004151014196_deneme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
